export const STORE = {
  company: {
    name: 'SEPANG GROUP ЕООД',
    brand: 'WAGNER-BG',
    email: 'sepanggroupltd@gmail.com'
  },
  categories: [
    { id: 'airless', name: 'Airless боядисване', desc: 'Професионални системи за дисперсии, латекс, фасадни бои, грундове и други покрития.' },
    { id: 'xvlp', name: 'XVLP / HVLP', desc: 'Системи за лакове, емайли, дърво, метал и фини довършителни приложения.' },
    { id: 'guns', name: 'Пистолети и дюзи', desc: 'Професионални airless пистолети, HEA дюзи и компоненти за различни системи.' },
    { id: 'accessories', name: 'Аксесоари', desc: 'Маркучи, филтри, дюзи, удължители и сервизни компоненти.' },
    { id: 'preparation', name: 'Подготовка', desc: 'Решения за подготовка и ремонт преди нанасяне на покрития.' }
  ],
  products: [
    { id: 'prospray-320-hea', category: 'airless', name: 'ProSpray 3.20 HEA', model: 'PS 3.20 HEA', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS HEA', blurb: 'Компактна професионална airless система за средни обекти и интериорни емулсионни бои.', priceKnown: true, price: 1687.26, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; крайната цена и наличност се потвърждават преди покупка.', priceSource: 'Etools.bg', imageUrl: 'https://www.bricoman.pl/media/catalog/product/4/4/2/2/agregat_malarski_prospray_hea_wagner_10466022_picture.jpeg?bg-color=255%2C255%2C255&canvas=400%3A400&fit=bounds&height=700&quality=80&width=700', referenceUrl: 'https://etools.bg/category/3285/mashini-za-boyadisvane-wagner.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/prospray-320-hea-spraypack/', specs: ['Макс. налягане: 207 bar', 'Дебит: 2,0 l/min', 'Макс. дюза: 0,021″', 'Мотор: 1,0 kW'] },
    { id: 'control-pro-300-move', category: 'airless', name: 'Control Pro 300 Move', model: 'Control Pro 300 Move', eyebrow: 'WAGNER · AIRLESS · 18 V', blurb: 'Мобилна акумулаторна airless система за ремонтни и средни задачи с контролирано разпрашаване.', priceKnown: true, price: 843.12, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; крайната цена и конфигурацията се потвърждават преди покупка.', priceSource: 'Etools.bg', imageUrl: 'https://asset.conrad.com/media10/isa/160267/c1/-/en/002202092PI00/image.jpg', referenceUrl: 'https://etools.bg/product/57695/akumulatorna-bezvazdushna-mashina-za-praskane-na-boi-wagner-control-pro-300-move-18-v-0-9-l-min.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/control-pro-300-move/', specs: ['Захранване: 18 V', 'Дебит: 0,9 l/min', 'Налягане: 110 bar', 'Резервоар: 4,7 l'] },
    { id: 'superfinish-21-pro-hea', category: 'airless', name: 'SuperFinish 21 Pro HEA', model: 'SF 21 PRO HEA', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS HEA', blurb: 'Компактна професионална диафрагмена помпа за емулсии, латекс и други покрития при средни проекти.', priceKnown: true, price: 1477.63, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; крайната цена се потвърждава преди покупка.', priceSource: 'Etools.bg', imageUrl: 'https://cdn.sw.verfwebwinkel.nl/media/4e/g0/9d/1720368209/01908def9c4573808fc1d765990a1188.webp?ts=1720368209', referenceUrl: 'https://etools.bg/product/57574/elektricheska-profesionalna-bezvazdushna-mashina-za-praskane-na-boi-wagner-superfinish-21-pro-hea-900-w.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-21-pro-hea/', specs: ['Мотор: 0,9 kW', 'Дебит: 2,1 l/min', 'Налягане: 207 bar', 'Макс. дюза: 0,021″'] },
    { id: 'superfinish-23-pro-cart-hea', category: 'airless', name: 'SuperFinish 23 Pro Cart HEA', model: 'SuperFinish 23 Pro', eyebrow: 'WAGNER PROFESSIONAL · CART HEA', blurb: 'Здрава професионална диафрагмена машина за лакове, грундове, дисперсии, латекс и фасадни покрития.', priceKnown: true, price: 2249.17, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; комплектът и наличността се потвърждават преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://gomagcdn.ro/domains/conti.ro/files/product/original/pompa-airless-cu-membrana-pentru-zugravit-wagner-superfinish-23-pro-cart-hea-1300-w-debit-2-6-l-min-330573.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-superfinish-23-pro-cart-hea-22-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-23-pro-spraypack/', specs: ['Мотор: 1,3 kW', 'Дебит: 2,6 l/min', 'Налягане: 250 bar', 'Тегло: 29 kg'] },
    { id: 'prospray-325-cart', category: 'airless', name: 'ProSpray 3.25 Spraypack Cart', model: 'ProSpray 3.25', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS', blurb: 'Мобилна професионална система за емулсии, грундове, масла и фасадни бои при малки и средни обекти.', priceKnown: true, price: 3220.63, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; комплектът и наличността се потвърждават преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://static-eu-data.manualslib.com/product-images/a76/412194/wagner-ps-3-21-spritzpistolen-d%C3%BCsen-spritzen.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-prospray-325-spraypack-cart-13kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/ps-325-airless-spraypack/', specs: ['Мотор: 1,1 kW', 'Дебит: 2,6 l/min', 'Налягане: 221 bar', 'Макс. дюза: 0,027″'] },
    { id: 'superfinish-33-pro', category: 'airless', name: 'SuperFinish 33 Pro', model: 'SF 33 PRO', eyebrow: 'WAGNER PROFESSIONAL · HIGH OUTPUT', blurb: 'Високопроизводителна диафрагмена система за вътрешни и външни проекти и широк спектър покрития.', priceKnown: true, price: 4856.76, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; наличност и финална оферта се потвърждават преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://wagnerstore.com/wp-content/uploads/2023/09/697-bomba-de-diafragma-de-membrana-para-interior-y-exterior.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-superfinish-33-pro-22-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-33/', specs: ['Мотор: 2,2 kW', 'Дебит: 4,3 l/min', 'Налягане: 250 bar', 'Макс. дюза: 0,033″'] },
    { id: 'pp90-extra-hea', category: 'airless', name: 'PowerPainter PP 90 Extra HEA', model: 'PP 90 Extra HEA', eyebrow: 'WAGNER · AIRLESS HEA', blurb: 'Компактна airless система за малки и средни строителни и ремонтни задачи с ниско разпръскване.', priceKnown: true, price: 1017.47, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; крайната цена и наличността се потвърждават преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://www.sualati.com/files/product_picture/60e3040a19633_121.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-powerpainter-pp-90-extra-hea-08-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/powerpainter-90-extra/', specs: ['Мотор: 0,8 kW', 'Дебит: 1,9 l/min', 'Налягане: 207 bar', 'Макс. дюза: 0,019″'] },
    { id: 'finishcontrol-4000-18v', category: 'xvlp', name: 'FinishControl 4000 18V', model: 'FinishControl 4000 18V', eyebrow: 'WAGNER · XVLP · CORDLESS', blurb: 'Акумулаторна XVLP система за по-малки обекти, ремонт и фино боядисване на дърво и метал.', priceKnown: true, price: 802.21, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; конфигурацията на батерия и зарядно се потвърждава преди покупка.', priceSource: 'Etools.bg', imageUrl: 'https://www.magasindepeinture.ch/images/detailed/21/csm_2453688_FC4000-18V_product-shot_set_wo-background_207c02eb4f.jpg', referenceUrl: 'https://etools.bg/product/57630/akumulatoren-pistolet-za-boyadisvane-na-lateks-i-blazhni-boi-wagner-finish-control-4000-xvlp-18-v.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/finishcontrol-4000-18v-finespray/', specs: ['Захранване: 18 V', 'Технология: XVLP/HVLP', 'Налягане: 0,2 bar', 'Контейнер: 1.000 ml'] },
    { id: 'finishcontrol-5500', category: 'xvlp', name: 'FinishControl 5500', model: 'FinishControl 5500', eyebrow: 'WAGNER · XVLP · 230 V', blurb: 'Професионална XVLP система за боядисване, ретуш и обновяване с бърза смяна на приставките.', priceKnown: true, price: 741.37, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; потвърди крайната цена и комплектацията преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://spritzgeraete-shop.de/media/e3/e5/5d/1686911405/2422986_FC5500_product_back.jpg', referenceUrl: 'https://www.mashini.bg/pistolet-za-boyadivane-wagner-finish-control-5500-230v', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/finishcontrol-5500/', specs: ['Мощност: 1,15 kW', 'Налягане: 0,29 bar', 'Маркуч: 5 m', 'Тегло: 6,6 kg'] },
    { id: 'ac4500-greenair', category: 'guns', name: 'AC4500 GreenAir Professional', model: 'AC4500 GreenAir', eyebrow: 'WAGNER · AIRLESS / AIRCOAT GUN', blurb: 'Професионален пистолет за съвместими WAGNER системи и прецизно нанасяне на покрития.', priceKnown: true, price: 403.41, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; съвместимостта се потвърждава преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://spritzgeraete-shop.de/media/72/ed/9f/1633606387/2368270_AC4500_AC_Duese_gr%C3%BCn_vr.jpg', referenceUrl: 'https://www.mashini.bg/wagner-pistoleti-za-boyadisvane', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/building-trade/', specs: ['Професионално изпълнение', 'Airless / AirCoat приложение', 'Съвместимост според системата'] },
    { id: 'vectorpro-4-finger', category: 'guns', name: 'VectorPro 4 Finger Professional', model: 'VectorPro 4 Finger', eyebrow: 'WAGNER · AIRLESS GUN', blurb: 'Ергономичен професионален airless пистолет за бои, емулсии и латекс при до 250 bar.', priceKnown: true, price: 234.68, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Публична референтна цена; съвместимостта се потвърждава преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://www.paintsprayer.co.uk/media/catalog/product/5/3/538040_airless-gun_vector-pro_4-finger_product-shot_side.jpg?height=700&image-type=image&store=default&width=700', referenceUrl: 'https://www.mashini.bg/boyadzhiyski-bezvazdushen-pistolet-wagner-vectorpro-4-finger-professional-250-bara', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/building-trade/', specs: ['Макс. налягане: 250 bar', 'Тегло: 0,599 kg', 'За бои, емулсии и латекс'] }
  ]
};

export const getCategory = (id) => STORE.categories.find((item) => item.id === id);
export const getProduct = (id) => STORE.products.find((item) => item.id === id);
