export const STORE = {
  company: {
    name: 'КОЛМАН ЕООД',
    brand: 'WAGNER',
    email: 'kolmaneood@abv.bg',
    eik: '200736602',
    phone: '+359 88 579 66 13'
  },
  categories: [
    { id: 'airless', name: 'Airless боядисване', desc: 'Професионални системи за дисперсии, латекс, фасадни бои, грундове и други покрития.' },
    { id: 'xvlp', name: 'XVLP / HVLP', desc: 'Системи за лакове, емайли, дърво, метал и фини довършителни приложения.' },
    { id: 'filler', name: 'Шпакловка и замазка', desc: 'Високопроизводителни решения за спрей шпакловка и тежки строителни материали.' },
    { id: 'guns', name: 'Пистолети и дюзи', desc: 'Професионални airless пистолети, HEA дюзи и компоненти за различни системи.' },
    { id: 'accessories', name: 'Аксесоари', desc: 'Маркучи, филтри, дюзи, удължители и сервизни компоненти.' },
    { id: 'preparation', name: 'Подготовка', desc: 'Решения за подготовка и ремонт преди нанасяне на покрития.' },
    { id: 'robots', name: 'Роботи за полагане на плочки', desc: 'Автоматизирани решения за нанасяне на лепило, позициониране и полагане на подови плочки.' }
  ],
  products: [
    { id: 'prospray-320-hea', category: 'airless', name: 'ProSpray 3.20 HEA', model: 'PS 3.20 HEA', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS HEA', blurb: 'Компактна професионална airless система за средни обекти и интериорни емулсионни бои.', priceKnown: true, price: 1687.26, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; крайната цена и наличност се потвърждават от КОЛМАН ЕООД.', priceSource: 'Etools.bg', imageUrl: 'https://www.bricoman.pl/media/catalog/product/4/4/2/2/agregat_malarski_prospray_hea_wagner_10466022_picture.jpeg?bg-color=255%2C255%2C255&canvas=400%3A400&fit=bounds&height=700&quality=80&width=700', referenceUrl: 'https://etools.bg/category/3285/mashini-za-boyadisvane-wagner.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/prospray-320-hea-spraypack/', specs: ['Макс. налягане: 207 bar', 'Дебит: 2,0 l/min', 'Макс. дюза: 0,021″', 'Мотор: 1,0 kW'] },
    { id: 'control-pro-300-move', category: 'airless', name: 'Control Pro 300 Move', model: 'Control Pro 300 Move', eyebrow: 'WAGNER · AIRLESS · 18 V', blurb: 'Мобилна акумулаторна airless система за ремонтни и средни задачи с контролирано разпрашаване.', priceKnown: true, price: 843.12, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; потвърди крайната цена и конфигурацията преди покупка.', priceSource: 'Etools.bg', imageUrl: 'https://asset.conrad.com/media10/isa/160267/c1/-/en/002202092PI00/image.jpg', referenceUrl: 'https://etools.bg/product/57695/akumulatorna-bezvazdushna-mashina-za-praskane-na-boi-wagner-control-pro-300-move-18-v-0-9-l-min.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/control-pro-300-move/', specs: ['Захранване: 18 V', 'Дебит: 0,9 l/min', 'Налягане: 110 bar', 'Резервоар: 4,7 l'] },
    { id: 'superfinish-21-pro-hea', category: 'airless', name: 'SuperFinish 21 Pro HEA', model: 'SF 21 PRO HEA', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS HEA', blurb: 'Компактна професионална диафрагмена помпа за емулсии, латекс и други покрития при средни проекти.', priceKnown: true, price: 1477.63, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; цената на КОЛМАН ЕООД се потвърждава отделно.', priceSource: 'Etools.bg', imageUrl: 'https://cdn.sw.verfwebwinkel.nl/media/4e/g0/9d/1720368209/01908def9c4573808fc1d765990a1188.webp?ts=1720368209', referenceUrl: 'https://etools.bg/product/57574/elektricheska-profesionalna-bezvazdushna-mashina-za-praskane-na-boi-wagner-superfinish-21-pro-hea-900-w.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-21-pro-hea/', specs: ['Мотор: 0,9 kW', 'Дебит: 2,1 l/min', 'Налягане: 207 bar', 'Макс. дюза: 0,021″'] },
    { id: 'superfinish-23-pro-cart-hea', category: 'airless', name: 'SuperFinish 23 Pro Cart HEA', model: 'SuperFinish 23 Pro', eyebrow: 'WAGNER PROFESSIONAL · CART HEA', blurb: 'Здрава професионална диафрагмена машина за лакове, грундове, дисперсии, латекс и фасадни покрития.', priceKnown: true, price: 2249.17, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; крайната цена, комплектът и наличността се потвърждават от КОЛМАН ЕООД.', priceSource: 'Mashini.bg', imageUrl: 'https://gomagcdn.ro/domains/conti.ro/files/product/original/pompa-airless-cu-membrana-pentru-zugravit-wagner-superfinish-23-pro-cart-hea-1300-w-debit-2-6-l-min-330573.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-superfinish-23-pro-cart-hea-22-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-23-pro-spraypack/', specs: ['Мотор: 1,3 kW', 'Дебит: 2,6 l/min', 'Налягане: 250 bar', 'Тегло: 29 kg'] },
    { id: 'prospray-325-cart', category: 'airless', name: 'ProSpray 3.25 Spraypack Cart', model: 'ProSpray 3.25', eyebrow: 'WAGNER PROFESSIONAL · AIRLESS', blurb: 'Мобилна професионална система за емулсии, грундове, масла и фасадни бои при малки и средни обекти.', priceKnown: true, price: 3220.63, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; крайната цена и комплектът се потвърждават преди поръчка.', priceSource: 'Mashini.bg', imageUrl: 'https://static-eu-data.manualslib.com/product-images/a76/412194/wagner-ps-3-21-spritzpistolen-d%C3%BCsen-spritzen.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-prospray-325-spraypack-cart-13kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/ps-325-airless-spraypack/', specs: ['Мотор: 1,1 kW', 'Дебит: 2,6 l/min', 'Налягане: 221 bar', 'Макс. дюза: 0,027″'] },
    { id: 'superfinish-33-pro', category: 'airless', name: 'SuperFinish 33 Pro', model: 'SF 33 PRO', eyebrow: 'WAGNER PROFESSIONAL · HIGH OUTPUT', blurb: 'Високопроизводителна диафрагмена система за вътрешни и външни проекти и широк спектър покрития.', priceKnown: true, price: 4856.76, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; наличност и финална оферта се потвърждават от КОЛМАН ЕООД.', priceSource: 'Mashini.bg', imageUrl: 'https://wagnerstore.com/wp-content/uploads/2023/09/697-bomba-de-diafragma-de-membrana-para-interior-y-exterior.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-superfinish-33-pro-22-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/superfinish-33/', specs: ['Мотор: 2,2 kW', 'Дебит: 4,3 l/min', 'Налягане: 250 bar', 'Макс. дюза: 0,033″'] },
    { id: 'pp90-extra-hea', category: 'airless', name: 'PowerPainter PP 90 Extra HEA', model: 'PP 90 Extra HEA', eyebrow: 'WAGNER · AIRLESS HEA', blurb: 'Компактна airless система за малки и средни строителни и ремонтни задачи с ниско разпръскване.', priceKnown: true, price: 1017.47, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; потвърди крайната цена и наличността.', priceSource: 'Mashini.bg', imageUrl: 'https://www.sualati.com/files/product_picture/60e3040a19633_121.jpg', referenceUrl: 'https://www.mashini.bg/bezvazdushno-boyadzhiyska-mashina-wagner-powerpainter-pp-90-extra-hea-08-kw', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/powerpainter-90-extra/', specs: ['Мотор: 0,8 kW', 'Дебит: 1,9 l/min', 'Налягане: 207 bar', 'Макс. дюза: 0,019″'] },
    { id: 'finishcontrol-4000-18v', category: 'xvlp', name: 'FinishControl 4000 18V', model: 'FinishControl 4000 18V', eyebrow: 'WAGNER · XVLP · CORDLESS', blurb: 'Акумулаторна XVLP система за по-малки обекти, ремонт и фино боядисване на дърво и метал.', priceKnown: true, price: 802.21, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; конфигурацията на батерия и зарядно трябва да се потвърди.', priceSource: 'Etools.bg', imageUrl: 'https://www.magasindepeinture.ch/images/detailed/21/csm_2453688_FC4000-18V_product-shot_set_wo-background_207c02eb4f.jpg', referenceUrl: 'https://etools.bg/product/57630/akumulatoren-pistolet-za-boyadisvane-na-lateks-i-blazhni-boi-wagner-finish-control-4000-xvlp-18-v.html', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/finishcontrol-4000-18v-finespray/', specs: ['Захранване: 18 V', 'Технология: XVLP/HVLP', 'Налягане: 0,2 bar', 'Контейнер: 1.000 ml'] },
    { id: 'finishcontrol-5500', category: 'xvlp', name: 'FinishControl 5500', model: 'FinishControl 5500', eyebrow: 'WAGNER · XVLP · 230 V', blurb: 'Професионална XVLP система за боядисване, ретуш и обновяване с бърза смяна на приставките.', priceKnown: true, price: 741.37, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; потвърди крайната цена и комплектацията.', priceSource: 'Mashini.bg', imageUrl: 'https://spritzgeraete-shop.de/media/e3/e5/5d/1686911405/2422986_FC5500_product_back.jpg', referenceUrl: 'https://www.mashini.bg/pistolet-za-boyadivane-wagner-finish-control-5500-230v', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/product/finishcontrol-5500/', specs: ['Мощност: 1,15 kW', 'Налягане: 0,29 bar', 'Маркуч: 5 m', 'Тегло: 6,6 kg'] },
    { id: 'ac4500-greenair', category: 'guns', name: 'AC4500 GreenAir Professional', model: 'AC4500 GreenAir', eyebrow: 'WAGNER · AIRLESS / AIRCOAT GUN', blurb: 'Професионален пистолет за съвместими WAGNER системи и прецизно нанасяне на покрития.', priceKnown: true, price: 403.41, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; съвместимостта и точната конфигурация се потвърждават преди покупка.', priceSource: 'Mashini.bg', imageUrl: 'https://spritzgeraete-shop.de/media/72/ed/9f/1633606387/2368270_AC4500_AC_Duese_gr%C3%BCn_vr.jpg', referenceUrl: 'https://www.mashini.bg/wagner-pistoleti-za-boyadisvane', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/building-trade/', specs: ['Професионално изпълнение', 'Airless / AirCoat приложение', 'Съвместимост според системата'] },
    { id: 'vectorpro-4-finger', category: 'guns', name: 'VectorPro 4 Finger Professional', model: 'VectorPro 4 Finger', eyebrow: 'WAGNER · AIRLESS GUN', blurb: 'Ергономичен професионален airless пистолет за бои, емулсии и латекс при до 250 bar.', priceKnown: true, price: 234.68, priceCurrency: 'EUR', priceType: 'market-reference', priceNote: 'Референтна публична онлайн цена; потвърди съвместимостта с конкретната машина.', priceSource: 'Mashini.bg', imageUrl: 'https://www.paintsprayer.co.uk/media/catalog/product/5/3/538040_airless-gun_vector-pro_4-finger_product-shot_side.jpg?height=700&image-type=image&store=default&width=700', referenceUrl: 'https://www.mashini.bg/boyadzhiyski-bezvazdushen-pistolet-wagner-vectorpro-4-finger-professional-250-bara', officialUrl: 'https://www.wagner-group.com/en/contractor/products-and-accessories/building-trade/', specs: ['Макс. налягане: 250 bar', 'Тегло: 0,599 kg', 'За бои, емулсии и латекс'] },
    { id: 'kaifeng-tile-robot', category: 'robots', name: 'Automatic Tile Laying Robot · Kaifeng Yucheng', model: 'Automatic Tile Laying Robot', eyebrow: 'CONSTRUCTION ROBOT · TILE LAYING', blurb: 'Автоматизиран робот за полагане на подови плочки; публична обява за автоматизирана система.', priceKnown: true, price: 80000, priceMax: 80000, priceCurrency: 'USD', priceType: 'market-reference', priceNote: 'Публична Alibaba оферта; цена, спецификация, доставка и CE/ЕС съответствие се потвърждават преди покупка.', priceSource: 'Alibaba', imageUrl: 'https://s.alicdn.com/%40sc04/kf/H06cc4adfc42946918eb7c270df9593e6w/Automatic-Tile-Installation-Robot-Labor-saving-Floor-Tile-Laying-Machine-Smart-Construction-Robot-for-Tile-Paving.jpg', referenceUrl: 'https://www.alibaba.com/showroom/automatic-tile-laying-robot.html', specs: ['MOQ: 1 машина', 'Автоматично полагане на плочки', 'Kaifeng Yucheng Precision Machinery Co., Ltd.'] },
    { id: 'bossgoo-intelligent-tile-robot', category: 'robots', name: 'Intelligent Tile Laying Robot for Constructions', model: 'Intelligent Tile Laying Robot', eyebrow: 'CONSTRUCTION ROBOT · SLAM', blurb: 'Интелигентен робот, който интегрира нанасянето на лепило и автоматичното полагане на подови плочки.', priceKnown: true, price: 95000, priceMax: 165000, priceCurrency: 'USD', priceType: 'market-reference-range', priceNote: 'Публичен диапазон от Bossgoo; крайната цена, конфигурацията, транспортът и съответствието се потвърждават.', priceSource: 'Bossgoo', imageUrl: 'https://s.alicdn.com/%40sc04/kf/Hfafbbcfd02144fedab04d8b9c21567cdr.jpg_640x640.jpg', referenceUrl: 'https://www.bossgoo.com/product-detail/intelligent-tile-laying-robot-for-constructions-68275621.html', specs: ['600×600 / 800×800 / 1200×600 mm', 'Laser SLAM navigation', 'Прецизно нанасяне на лепило', 'Четириточкова вибрационна система'] },
    { id: 'bossgoo-palletizer-tile-robot', category: 'robots', name: 'Palletizer Stacking Machine Robot Tile Laying Robot', model: 'Tile Laying Robot', eyebrow: 'CONSTRUCTION ROBOT · AUTOMATION', blurb: 'Автоматизиран робот с интегрирано нанасяне на лепило и полагане на подови плочки.', priceKnown: true, price: 85000, priceMax: 155000, priceCurrency: 'USD', priceType: 'market-reference-range', priceNote: 'Публичен диапазон от Bossgoo; потвърди конфигурацията, транспортните условия и всички документи.', priceSource: 'Bossgoo', imageUrl: 'https://s.alicdn.com/%40sc04/kf/Hfafbbcfd02144fedab04d8b9c21567cdr.jpg_640x640.jpg', referenceUrl: 'https://www.bossgoo.com/product-detail/palletizer-stacking-machine-robot-tile-laying-68275606.html', specs: ['600×600 / 800×800 / 1200×600 mm', 'Laser SLAM navigation', 'Нанасяне на лепило + полагане', 'MOQ: 1 машина'] },
    { id: 'mrofed-electric-tile-robot', category: 'robots', name: 'Tile Laying Robot Electric for Construction Works', model: 'Tile Laying Robot Electric', eyebrow: 'CONSTRUCTION ROBOT · ELECTRIC', blurb: 'Електрически робот за автоматизирано полагане на подови плочки с интегрирано нанасяне на лепило.', priceKnown: true, price: 98000, priceMax: 165000, priceCurrency: 'USD', priceType: 'market-reference-range', priceNote: 'Публичен диапазон от MROFED; потвърди търговските условия, доставка и документация.', priceSource: 'MROFED', imageUrl: 'https://s.alicdn.com/%40sc04/kf/Hfafbbcfd02144fedab04d8b9c21567cdr.jpg_640x640.jpg', referenceUrl: 'https://www.mrofed.com/dp-tile-laying-robot-k7347185.html', specs: ['600×600 / 800×800 / 1200×600 mm', 'Laser SLAM navigation', 'Интегрирано нанасяне на лепило', 'Интегрирано полагане на плочката'] },
    { id: 'partner-p900', category: 'robots', name: 'Partner Robotics P900 Floor Tile Paving Robot', model: 'P900', eyebrow: 'PARTNER ROBOTICS · FLOOR TILE PAVING', blurb: 'Професионален робот за автоматизирано полагане на подови плочки с висока производителност и работа на реални обекти.', priceKnown: false, price: null, priceCurrency: 'USD', priceType: 'quote', priceNote: 'Цена по оферта от производителя.', priceSource: 'Partner Robotics', imageUrl: 'https://constructmagazine.com/wp-content/uploads/2025/11/Floor-Tile-Paving-Robot.png', referenceUrl: 'https://www.partnerrobotics.com/pages/floor-tile-paving-robot', specs: ['До 18 m²/h', 'Payload: 30 kg', 'Над 6 h автономност', 'Размер: 1300×800×1950 mm'] },
    { id: 'legend-tile-robot', category: 'robots', name: 'Legend Floor Tile Laying Robot', model: 'Legend Tile Laying Robot', eyebrow: 'LEGEND ROBOTICS · TILE LAYING', blurb: 'Робот за автоматизирано нанасяне на лепило и полагане на подови плочки с човешко-роботизирана работа.', priceKnown: false, price: null, priceCurrency: 'USD', priceType: 'quote', priceNote: 'Цена по оферта; необходимо е потвърждение на конфигурацията.', priceSource: 'Legend Robot', imageUrl: 'https://www.legendrobot.cn/upload/2024/03/19/xfsy8t77yfc611710840303.jpg', referenceUrl: 'https://www.legendrobot.cn/products/tile-laying-robot/', specs: ['600×600 / 800×800 mm', '600 kg', '60 L резервоар за разтвор', '80–120 плочки/ден'] }
  ]
};

export const getCategory = (id) => STORE.categories.find((item) => item.id === id);
export const getProduct = (id) => STORE.products.find((item) => item.id === id);
