import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const index = read('index.html');
const app = read('app.js');
const cart = read('cart.js');
const payment = read('payment.js');
const merchant = read('merchant-config.js');

assert.match(index, /KOLMAN EOOD/);
assert.match(index, /kolmaneood@abv\.bg/);
assert.match(index, /id="product-grid"/);
assert.match(index, /id="paypal-button-container"/);
assert.match(index, /id="paypal-card-button-container"/);
assert.match(index, /id="paypal-payment-summary"/);
assert.match(index, /id="paypal-payment-items"/);
assert.match(index, /id="paypal-payment-total"/);
assert.match(app, /addToCart/);
assert.match(app, /buy-product/);
assert.match(app, /updateCartUI/);
assert.match(app, /initCartPayment/);
assert.match(app, /renderPaymentSummary/);
assert.match(cart, /CART_KEY/);
assert.match(cart, /cartSubtotal/);
assert.match(cart, /cartHasNonPurchasableItems/);
assert.match(cart, /KOLMAN EOOD/);
assert.doesNotMatch(merchant, /sepanggroupltd@gmail\.com/i);
assert.doesNotMatch(merchant, /\+359 88 579 66 13/);

assert.match(payment, /PayPal/);
assert.match(payment, /createOrder/);
assert.match(payment, /capture\(\)/);
assert.match(payment, /merchant-config\.js/);
assert.match(payment, /currency=EUR/);
assert.match(payment, /enable-funding=card/);
assert.match(payment, /FUNDING\.CARD/);
assert.match(payment, /paypal-card-button-container/);
assert.match(payment, /KOLMAN EOOD/);
assert.match(payment, /paypalReady/);
assert.match(payment, /https:\/\/www\.paypal\.com\/paypalme\/1968428713/);
assert.match(payment, /paypal-static-fallback/);
assert.match(payment, /PayPal\.Me/);
assert.doesNotMatch(payment, /https:\/\/www\.paypal\.com\/paypalme\/my\/grab/);
assert.doesNotMatch(payment, /https:\/\/www\.paypal\.com\/ncp\/payment\/653GFDV8Z76G2/);
assert.doesNotMatch(payment, /sepanggroupltd@gmail\.com/i);
assert.doesNotMatch(payment, /\+359 88 579 66 13/);
assert.doesNotMatch(payment, /staticFallback\.hidden = true/);

console.log('WAGNER source integrity contract passed');
